services:
  - type: web
    name: text-to-speech-app
    runtime: php
    plan: starter
    buildCommand: bash build.sh
    startCommand: bash start.sh
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: "Text to Speech Translator"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          type: web
          name: text-to-speech-app
          property: host
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: database/database.sqlite
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: FILESYSTEM_DISK
        value: local
      - key: BROADCAST_DRIVER
        value: log
      - key: ELEVEN_LABS_API_KEY
        value: sk_1a24c5398c4e11fae83a0d9a14cd9febecd44ebcf4dacd73
      - key: APP_LOCALE
        value: en
      - key: APP_FALLBACK_LOCALE
        value: en
      - key: BCRYPT_ROUNDS
        value: "12"
    autoDeploy: true